challenge_timeout: 60 # Sekunden
arenas:
kits:
  default:
    items:
      - iron_sword:1
      - golden_apple:5
    armor:
      - iron_helmet:1
      - iron_chestplate:1
      - iron_leggings:1
      - iron_boots:1
    effects:
      - regeneration:1:10 # Effekt-ID:Stärke:Dauer (in Sekunden)
  archer:
    items:
      - bow:1
      - arrow:64
    armor:
      - leather_helmet:1
      - leather_chestplate:1
      - leather_leggings:1
      - leather_boots:1
